"""tags

Revision ID: 00c972276039
Revises: f3a77efb9edf
Create Date: 2023-01-15 13:21:15.970678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c972276039'
down_revision = 'f3a77efb9edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_tags', 'id_media_tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_tags', sa.Column('id_media_tags', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
