"""add column date update feedback user bot

Revision ID: 09f3ff4750d6
Revises: 1bf3bda7c7eb
Create Date: 2023-04-05 17:06:21.056305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f3ff4750d6'
down_revision = '1bf3bda7c7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_to_feedback_bot', sa.Column('data_update', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_to_feedback_bot', 'data_update')
    # ### end Alembic commands ###
