"""unique id chanel

Revision ID: 262d7a4454ed
Revises: 30c64c1bbb63
Create Date: 2023-01-14 09:47:32.719671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262d7a4454ed'
down_revision = '30c64c1bbb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chanels', ['id_telegram'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chanels', type_='unique')
    # ### end Alembic commands ###
