"""add msg feedback bot change on bigint

Revision ID: 2acd507ba9d4
Revises: 351f5c420739
Create Date: 2023-04-08 14:33:30.172715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2acd507ba9d4'
down_revision = '351f5c420739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_to_feedback_bot',
    sa.Column('id_users_to_feedback_bot', sa.Integer(), nullable=False),
    sa.Column('id_feedback_bot', sa.Integer(), nullable=True),
    sa.Column('id_user_telegram', sa.BigInteger(), nullable=False),
    sa.Column('name_user', sa.String(length=100), nullable=False),
    sa.Column('data_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_feedback_bot'], ['feedback_bots.id_feedback_bot'], ),
    sa.PrimaryKeyConstraint('id_users_to_feedback_bot'),
    sa.UniqueConstraint('id_user_telegram', 'id_feedback_bot', name='_user_bot_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_to_feedback_bot')
    # ### end Alembic commands ###
