"""add table feedback bots1

Revision ID: 2e2ddd6bd83b
Revises: ea5fbae39d36
Create Date: 2023-04-04 14:40:39.444531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2ddd6bd83b'
down_revision = 'ea5fbae39d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'feedback_bots', ['token_bot'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback_bots', type_='unique')
    # ### end Alembic commands ###
