"""type password

Revision ID: 6ed7ef966f80
Revises: 05a38d1f9ff0
Create Date: 2023-01-11 13:23:05.973080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed7ef966f80'
down_revision = '05a38d1f9ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id_telegram',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id_telegram',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
