"""add msg feedback bot change on bigint

Revision ID: 9443de4e6305
Revises: 2acd507ba9d4
Create Date: 2023-04-08 14:35:06.844854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9443de4e6305'
down_revision = '2acd507ba9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ban_users_feedback_bot',
    sa.Column('id_ban_users_feedback_bot', sa.Integer(), nullable=False),
    sa.Column('id_user_telegram', sa.BigInteger(), nullable=False),
    sa.Column('id_feedback_bot', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_feedback_bot'], ['feedback_bots.id_feedback_bot'], ),
    sa.PrimaryKeyConstraint('id_ban_users_feedback_bot')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ban_users_feedback_bot')
    # ### end Alembic commands ###
