"""uniq pair tag chanel

Revision ID: b385027b702f
Revises: 3d5fda11924a
Create Date: 2023-01-25 19:10:09.082044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b385027b702f'
down_revision = '3d5fda11924a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_tag_channel_uc', 'tags', ['tag_name', 'id_channel'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_tag_channel_uc', 'tags', type_='unique')
    # ### end Alembic commands ###
