"""published

Revision ID: b8c785946144
Revises: c5eb4323f1f5
Create Date: 2023-01-28 16:11:17.589272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c785946144'
down_revision = 'c5eb4323f1f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
