"""unique id chanNel

Revision ID: bd5d3638b821
Revises: 262d7a4454ed
Create Date: 2023-01-14 12:12:01.118769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5d3638b821'
down_revision = '262d7a4454ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id_channel', sa.Integer(), nullable=False),
    sa.Column('name_channel', sa.String(length=200), nullable=False),
    sa.Column('link_channel', sa.String(length=200), nullable=False),
    sa.Column('id_telegram', sa.String(length=200), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('data_update', sa.DateTime(), nullable=False),
    sa.Column('id_user_admin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user_admin'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_channel'),
    sa.UniqueConstraint('id_telegram')
    )
    op.create_table('users_channels',
    sa.Column('id_user_channel', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_channel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_channel'], ['channels.id_channel'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_user_channel')
    )
    op.add_column('events', sa.Column('id_channel', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'channels', ['id_channel'], ['id_channel'])
    op.drop_column('events', 'id_chanel')
    op.add_column('tags', sa.Column('id_channel', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'channels', ['id_channel'], ['id_channel'])
    op.drop_column('tags', 'id_chanel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('id_chanel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'id_channel')
    op.add_column('events', sa.Column('id_chanel', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'id_channel')
    op.drop_table('users_channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
