"""test

Revision ID: c5eb4323f1f5
Revises: 
Create Date: 2023-01-28 16:09:41.421051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5eb4323f1f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('published', sa.Boolean(), nullable=True))
    op.alter_column('events', 'id_message',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'id_message',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('events', 'published')
    # ### end Alembic commands ###
