"""posts

Revision ID: d12deeb0a879
Revises: bd5d3638b821
Create Date: 2023-01-14 15:37:14.064445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12deeb0a879'
down_revision = 'bd5d3638b821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'id_post_media')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('id_post_media', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
