"""add table feedback bots

Revision ID: ea5fbae39d36
Revises: 22b5259e727f
Create Date: 2023-04-04 10:06:50.721934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5fbae39d36'
down_revision = '22b5259e727f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_bots',
    sa.Column('id_feedback_bot', sa.Integer(), nullable=False),
    sa.Column('token_bot', sa.String(length=100), nullable=False),
    sa.Column('name_bot', sa.String(length=100), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('data_update', sa.DateTime(), nullable=False),
    sa.Column('is_archive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_feedback_bot')
    )
    op.create_table('users_to_feedback_bot',
    sa.Column('id_users_to_feedback_bot', sa.Integer(), nullable=False),
    sa.Column('id_feedback_bot', sa.Integer(), nullable=True),
    sa.Column('id_user_telegram', sa.String(length=100), nullable=False),
    sa.Column('name_user', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_feedback_bot'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_users_to_feedback_bot'),
    sa.UniqueConstraint('id_user_telegram', 'id_feedback_bot', name='_user_bot_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_to_feedback_bot')
    op.drop_table('feedback_bots')
    # ### end Alembic commands ###
