"""many to many

Revision ID: f3a77efb9edf
Revises: d12deeb0a879
Create Date: 2023-01-15 08:26:15.134879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a77efb9edf'
down_revision = 'd12deeb0a879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts_media', 'id_post_media')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts_media', sa.Column('id_post_media', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
