"""add post date create and date update

Revision ID: f80efe54b08b
Revises: b385027b702f
Create Date: 2023-01-27 13:21:14.551068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80efe54b08b'
down_revision = 'b385027b702f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date_create', sa.DateTime(), nullable=False))
    op.add_column('posts', sa.Column('data_update', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'data_update')
    op.drop_column('posts', 'date_create')
    # ### end Alembic commands ###
